global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "java-serviece"
    scrape_interval: 5s
    static_configs:
    - targets: ["service_java:8080"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]