global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "java-serviece"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ["service-java:8080"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]